[theme]
base = "light"
primaryColor = "#0B67C2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F7FB"
textColor = "#252936"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
